//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------
using Client.Server.Models;

namespace Client.Server.Services
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IDriverService")]
    public interface IDriverService
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDriverService/GetAll", ReplyAction = "http://tempuri.org/IDriverService/GetAllResponse")]
        Driver[] GetAll();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDriverService/GetAll", ReplyAction = "http://tempuri.org/IDriverService/GetAllResponse")]
        System.Threading.Tasks.Task<Driver[]> GetAllAsync();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDriverService/Add", ReplyAction = "http://tempuri.org/IDriverService/AddResponse")]
        bool Add(Driver driver);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDriverService/Add", ReplyAction = "http://tempuri.org/IDriverService/AddResponse")]
        System.Threading.Tasks.Task<bool> AddAsync(Driver driver);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDriverService/UpdateDriver", ReplyAction = "http://tempuri.org/IDriverService/UpdateDriverResponse")]
        bool UpdateDriver(int driverId, Driver driver);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDriverService/UpdateDriver", ReplyAction = "http://tempuri.org/IDriverService/UpdateDriverResponse")]
        System.Threading.Tasks.Task<bool> UpdateDriverAsync(int driverId, Driver driver);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDriverService/UpdateFirstName", ReplyAction = "http://tempuri.org/IDriverService/UpdateFirstNameResponse")]
        bool UpdateFirstName(int driverId, string firstName);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDriverService/UpdateFirstName", ReplyAction = "http://tempuri.org/IDriverService/UpdateFirstNameResponse")]
        System.Threading.Tasks.Task<bool> UpdateFirstNameAsync(int driverId, string firstName);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDriverService/UpdateLastName", ReplyAction = "http://tempuri.org/IDriverService/UpdateLastNameResponse")]
        bool UpdateLastName(int driverId, string lastName);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDriverService/UpdateLastName", ReplyAction = "http://tempuri.org/IDriverService/UpdateLastNameResponse")]
        System.Threading.Tasks.Task<bool> UpdateLastNameAsync(int driverId, string lastName);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDriverService/UpdateEmployeeNumber", ReplyAction = "http://tempuri.org/IDriverService/UpdateEmployeeNumberResponse")]
        bool UpdateEmployeeNumber(int driverId, int employeeNumber);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDriverService/UpdateEmployeeNumber", ReplyAction = "http://tempuri.org/IDriverService/UpdateEmployeeNumberResponse")]
        System.Threading.Tasks.Task<bool> UpdateEmployeeNumberAsync(int driverId, int employeeNumber);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDriverService/UpdateAreas", ReplyAction = "http://tempuri.org/IDriverService/UpdateAreasResponse")]
        bool UpdateAreas(int driverId, Area[] areas);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDriverService/UpdateAreas", ReplyAction = "http://tempuri.org/IDriverService/UpdateAreasResponse")]
        System.Threading.Tasks.Task<bool> UpdateAreasAsync(int driverId, Area[] areas);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDriverService/Delete", ReplyAction = "http://tempuri.org/IDriverService/DeleteResponse")]
        bool Delete(int driverId);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDriverService/Delete", ReplyAction = "http://tempuri.org/IDriverService/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(int driverId);
    }
}
