//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------
using Client.Server.Models;

namespace Client.Server.Services
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IOrderLinesService")]
    public interface IOrderLinesService
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOrderLinesService/GetAll", ReplyAction = "http://tempuri.org/IOrderLinesService/GetAllResponse")]
        OrderLines[] GetAll();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOrderLinesService/GetAll", ReplyAction = "http://tempuri.org/IOrderLinesService/GetAllResponse")]
        System.Threading.Tasks.Task<OrderLines[]> GetAllAsync();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOrderLinesService/Add", ReplyAction = "http://tempuri.org/IOrderLinesService/AddResponse")]
        bool Add(OrderLines orderLines);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOrderLinesService/Add", ReplyAction = "http://tempuri.org/IOrderLinesService/AddResponse")]
        System.Threading.Tasks.Task<bool> AddAsync(OrderLines orderLines);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOrderLinesService/Delete", ReplyAction = "http://tempuri.org/IOrderLinesService/DeleteResponse")]
        bool Delete(int orderLinesId);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOrderLinesService/Delete", ReplyAction = "http://tempuri.org/IOrderLinesService/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(int orderLinesId);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOrderLinesService/UpdateAmount", ReplyAction = "http://tempuri.org/IOrderLinesService/UpdateAmountResponse")]
        bool UpdateAmount(int orderLinesId, int amount);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOrderLinesService/UpdateAmount", ReplyAction = "http://tempuri.org/IOrderLinesService/UpdateAmountResponse")]
        System.Threading.Tasks.Task<bool> UpdateAmountAsync(int orderLinesId, int amount);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOrderLinesService/UpdatePosition", ReplyAction = "http://tempuri.org/IOrderLinesService/UpdatePositionResponse")]
        bool UpdatePosition(int orderLinesId, int position);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOrderLinesService/UpdatePosition", ReplyAction = "http://tempuri.org/IOrderLinesService/UpdatePositionResponse")]
        System.Threading.Tasks.Task<bool> UpdatePositionAsync(int orderLinesId, int position);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOrderLinesService/UpdateOrder", ReplyAction = "http://tempuri.org/IOrderLinesService/UpdateOrderResponse")]
        bool UpdateOrder(int orderLinesId, Order order);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOrderLinesService/UpdateOrder", ReplyAction = "http://tempuri.org/IOrderLinesService/UpdateOrderResponse")]
        System.Threading.Tasks.Task<bool> UpdateOrderAsync(int orderLinesId, Order order);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOrderLinesService/UpdateArticle", ReplyAction = "http://tempuri.org/IOrderLinesService/UpdateArticleResponse")]
        bool UpdateArticle(int orderLinesId, Article article);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOrderLinesService/UpdateArticle", ReplyAction = "http://tempuri.org/IOrderLinesService/UpdateArticleResponse")]
        System.Threading.Tasks.Task<bool> UpdateArticleAsync(int orderLinesId, Article article);
    }
}