//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------
using Client.Server.Models;

namespace Client.Server.Services
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IOrderService")]
    public interface IOrderService
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOrderService/GetAll", ReplyAction = "http://tempuri.org/IOrderService/GetAllResponse")]
        Server.Models.Order[] GetAll();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOrderService/GetAll", ReplyAction = "http://tempuri.org/IOrderService/GetAllResponse")]
        System.Threading.Tasks.Task<Server.Models.Order[]> GetAllAsync();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOrderService/Add", ReplyAction = "http://tempuri.org/IOrderService/AddResponse")]
        bool Add(Server.Models.Order order);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOrderService/Add", ReplyAction = "http://tempuri.org/IOrderService/AddResponse")]
        System.Threading.Tasks.Task<bool> AddAsync(Server.Models.Order order);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOrderService/Delete", ReplyAction = "http://tempuri.org/IOrderService/DeleteResponse")]
        bool Delete(int orderId);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOrderService/Delete", ReplyAction = "http://tempuri.org/IOrderService/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(int orderId);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOrderService/UpdateOrder", ReplyAction = "http://tempuri.org/IOrderService/UpdateOrderResponse")]
        bool UpdateOrder(int orderId, Server.Models.Order order);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOrderService/UpdateOrder", ReplyAction = "http://tempuri.org/IOrderService/UpdateOrderResponse")]
        System.Threading.Tasks.Task<bool> UpdateOrderAsync(int orderId, Server.Models.Order order);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOrderService/UpdateOrderNumber", ReplyAction = "http://tempuri.org/IOrderService/UpdateOrderNumberResponse")]
        bool UpdateOrderNumber(int orderId, string orderNumber);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOrderService/UpdateOrderNumber", ReplyAction = "http://tempuri.org/IOrderService/UpdateOrderNumberResponse")]
        System.Threading.Tasks.Task<bool> UpdateOrderNumberAsync(int orderId, string orderNumber);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOrderService/UpdateOrderDate", ReplyAction = "http://tempuri.org/IOrderService/UpdateOrderDateResponse")]
        bool UpdateOrderDate(int orderId, System.DateTime orderDate);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOrderService/UpdateOrderDate", ReplyAction = "http://tempuri.org/IOrderService/UpdateOrderDateResponse")]
        System.Threading.Tasks.Task<bool> UpdateOrderDateAsync(int orderId, System.DateTime orderDate);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOrderService/UpdateDescription", ReplyAction = "http://tempuri.org/IOrderService/UpdateDescriptionResponse")]
        bool UpdateDescription(int orderId, string description);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOrderService/UpdateDescription", ReplyAction = "http://tempuri.org/IOrderService/UpdateDescriptionResponse")]
        System.Threading.Tasks.Task<bool> UpdateDescriptionAsync(int orderId, string description);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOrderService/UpdateDriver", ReplyAction = "http://tempuri.org/IOrderService/UpdateDriverResponse")]
        bool UpdateDriver(int orderId, Server.Models.Driver driver);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOrderService/UpdateDriver", ReplyAction = "http://tempuri.org/IOrderService/UpdateDriverResponse")]
        System.Threading.Tasks.Task<bool> UpdateDriverAsync(int orderId, Server.Models.Driver driver);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOrderService/UpdateCustomer", ReplyAction = "http://tempuri.org/IOrderService/UpdateCustomerResponse")]
        bool UpdateCustomer(int orderId, Server.Models.Customer customer);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOrderService/UpdateCustomer", ReplyAction = "http://tempuri.org/IOrderService/UpdateCustomerResponse")]
        System.Threading.Tasks.Task<bool> UpdateCustomerAsync(int orderId, Server.Models.Customer customer);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOrderService/UpdateOrderLines", ReplyAction = "http://tempuri.org/IOrderService/UpdateOrderLinesResponse")]
        bool UpdateOrderLines(int orderId, Server.Models.OrderLines[] orderLines);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOrderService/UpdateOrderLines", ReplyAction = "http://tempuri.org/IOrderService/UpdateOrderLinesResponse")]
        System.Threading.Tasks.Task<bool> UpdateOrderLinesAsync(int orderId, Server.Models.OrderLines[] orderLines);
    }
}