//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------
using Client.Server.Models;

namespace Client.Server.Services
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IOrderLinesService")]
    public interface IOrderLinesService
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOrderLinesService/GetAll", ReplyAction = "http://tempuri.org/IOrderLinesService/GetAllResponse")]
        OrderLines[] GetAll();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOrderLinesService/GetAll", ReplyAction = "http://tempuri.org/IOrderLinesService/GetAllResponse")]
        System.Threading.Tasks.Task<OrderLines[]> GetAllAsync();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOrderLinesService/Add", ReplyAction = "http://tempuri.org/IOrderLinesService/AddResponse")]
        bool Add(OrderLines orderLines);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOrderLinesService/Add", ReplyAction = "http://tempuri.org/IOrderLinesService/AddResponse")]
        System.Threading.Tasks.Task<bool> AddAsync(OrderLines orderLines);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOrderLinesService/Delete", ReplyAction = "http://tempuri.org/IOrderLinesService/DeleteResponse")]
        bool Delete(int orderLinesId);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOrderLinesService/Delete", ReplyAction = "http://tempuri.org/IOrderLinesService/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(int orderLinesId);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOrderLinesService/UpdateAmount", ReplyAction = "http://tempuri.org/IOrderLinesService/UpdateAmountResponse")]
        bool UpdateAmount(int orderLinesId, int amount);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOrderLinesService/UpdateAmount", ReplyAction = "http://tempuri.org/IOrderLinesService/UpdateAmountResponse")]
        System.Threading.Tasks.Task<bool> UpdateAmountAsync(int orderLinesId, int amount);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOrderLinesService/UpdatePosition", ReplyAction = "http://tempuri.org/IOrderLinesService/UpdatePositionResponse")]
        bool UpdatePosition(int orderLinesId, int position);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOrderLinesService/UpdatePosition", ReplyAction = "http://tempuri.org/IOrderLinesService/UpdatePositionResponse")]
        System.Threading.Tasks.Task<bool> UpdatePositionAsync(int orderLinesId, int position);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOrderLinesService/UpdateOrder", ReplyAction = "http://tempuri.org/IOrderLinesService/UpdateOrderResponse")]
        bool UpdateOrder(int orderLinesId, Order order);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOrderLinesService/UpdateOrder", ReplyAction = "http://tempuri.org/IOrderLinesService/UpdateOrderResponse")]
        System.Threading.Tasks.Task<bool> UpdateOrderAsync(int orderLinesId, Order order);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOrderLinesService/UpdateArticle", ReplyAction = "http://tempuri.org/IOrderLinesService/UpdateArticleResponse")]
        bool UpdateArticle(int orderLinesId, Article article);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOrderLinesService/UpdateArticle", ReplyAction = "http://tempuri.org/IOrderLinesService/UpdateArticleResponse")]
        System.Threading.Tasks.Task<bool> UpdateArticleAsync(int orderLinesId, Article article);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrderLinesServiceChannel : IOrderLinesService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderLinesServiceClient : System.ServiceModel.ClientBase<IOrderLinesService>, IOrderLinesService
    {

        public OrderLinesServiceClient()
        {
        }

        public OrderLinesServiceClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public OrderLinesServiceClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public OrderLinesServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public OrderLinesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public OrderLines[] GetAll()
        {
            return base.Channel.GetAll();
        }

        public System.Threading.Tasks.Task<OrderLines[]> GetAllAsync()
        {
            return base.Channel.GetAllAsync();
        }

        public bool Add(OrderLines orderLines)
        {
            return base.Channel.Add(orderLines);
        }

        public System.Threading.Tasks.Task<bool> AddAsync(OrderLines orderLines)
        {
            return base.Channel.AddAsync(orderLines);
        }

        public bool Delete(int orderLinesId)
        {
            return base.Channel.Delete(orderLinesId);
        }

        public System.Threading.Tasks.Task<bool> DeleteAsync(int orderLinesId)
        {
            return base.Channel.DeleteAsync(orderLinesId);
        }

        public bool UpdateAmount(int orderLinesId, int amount)
        {
            return base.Channel.UpdateAmount(orderLinesId, amount);
        }

        public System.Threading.Tasks.Task<bool> UpdateAmountAsync(int orderLinesId, int amount)
        {
            return base.Channel.UpdateAmountAsync(orderLinesId, amount);
        }

        public bool UpdatePosition(int orderLinesId, int position)
        {
            return base.Channel.UpdatePosition(orderLinesId, position);
        }

        public System.Threading.Tasks.Task<bool> UpdatePositionAsync(int orderLinesId, int position)
        {
            return base.Channel.UpdatePositionAsync(orderLinesId, position);
        }

        public bool UpdateOrder(int orderLinesId, Order order)
        {
            return base.Channel.UpdateOrder(orderLinesId, order);
        }

        public System.Threading.Tasks.Task<bool> UpdateOrderAsync(int orderLinesId, Order order)
        {
            return base.Channel.UpdateOrderAsync(orderLinesId, order);
        }

        public bool UpdateArticle(int orderLinesId, Article article)
        {
            return base.Channel.UpdateArticle(orderLinesId, article);
        }

        public System.Threading.Tasks.Task<bool> UpdateArticleAsync(int orderLinesId, Article article)
        {
            return base.Channel.UpdateArticleAsync(orderLinesId, article);
        }
    }
}